name: deep_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^0.11.0
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  dartz: ^0.9.1
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  
  auto_route: ^0.6.6
  
  flushbar: ^1.10.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.4
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  injectable_generator: ^0.4.1
  auto_route_generator: ^0.6.6
  flutter_launcher_icons: ^0.7.5


flutter_icons:
  android: true
  ios: true
  image_path: "assets/kambing.png"

flutter:
  assets:
    - assets/kambing.png
  uses-material-design: true
